Repository kubewarden/kubewarden-controller, pull requests merged in 2022-12, with the labels that each got.

#363 Upload CRDS and trigger Helm chart update.
  .github/workflows/release.yml
Labels: kind/chore, area/ci

#364 docs: Bump docs/crds to k8s 1.25
  docs/crds/README.asciidoc
  docs/crds/config.yml
Labels: documentation

#366 fix: autolabeler of issues
  .github/release-drafter.yml
Labels: kind/bug

#367 chore(deps): Bump x/net to 0.4.0
  go.mod
  go.sum
Labels: area/dependencies, kind/chore, release/patch

#370 Run autolabeler when a PR is edited
  .github/workflows/release-drafter.yml
Labels: kind/bug, area/ci

#372 Community meeting documentation.
  README.md
Labels: documentation, release/skip-changelog
