Repository kubewarden/kubewarden-controller, pull requests merged in 2023-10, with the labels that each got.

#553 fix!: Don't reconcile KUBEWARDEN_LOG_FMT envvar
  internal/pkg/admission/policy-server-deployment.go
  internal/pkg/admission/policy-server-deployment_test.go
  internal/pkg/constants/constants.go
Labels: kind/bug, kind/breaking-change

#555 Revert "fix!: Don't reconcile KUBEWARDEN_LOG_FMT envvar"
  internal/pkg/admission/policy-server-deployment.go
  internal/pkg/admission/policy-server-deployment_test.go
  internal/pkg/constants/constants.go
Labels: kind/bug, kind/breaking-change

#556 feat!: Add `--enable-tracing`, separate metrics and tracing reconciliation
  internal/pkg/admission/policy-server-deployment.go
  internal/pkg/admission/policy-server-deployment_test.go
  internal/pkg/admission/reconciler.go
  main.go
Labels: kind/feature, kind/breaking-change

#557 docs: Reformat CRD docstrings for automation into main docs site
  docs/crds/CRD-docs-for-docs-repo.md
  docs/crds/Makefile
  docs/crds/README.asciidoc
  docs/crds/README.md
  pkg/apis/policies/v1/clusteradmissionpolicy_types.go
  pkg/apis/policies/v1/policy_types.go
  pkg/apis/policies/v1alpha2/clusteradmissionpolicy_types.go
  pkg/apis/policies/v1alpha2/policy_types.go
Labels: area/documentation, area/crd

#560 chore(deps): update golang.org/x/net
  go.mod
  go.sum
Labels: area/dependencies, kind/chore

#563 chore(deps): update grpc dependency
  go.mod
  go.sum
Labels: area/dependencies, kind/chore

#566 feat: Always enforce `{Validating,Mutating}WebhookConfiguration` state
  controllers/admissionpolicy_controller.go
  controllers/clusteradmissionpolicy_controller.go
  controllers/policyserver_controller.go
  internal/pkg/admission/mutating-webhook.go
  internal/pkg/admission/validating-webhook.go
Labels: kind/feature
