Repository kubewarden/kubewarden-controller, pull requests merged in 2023-07, with the labels that each got.

#477 fix: updates cosign to v2.
  .github/workflows/container-build.yml
  .github/workflows/container-image.yml
  .github/workflows/release.yml
Labels: kind/enhancement, area/ci

#485 fix: GH action, reuse actions from the same checkout
  .github/workflows/container-build.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/release.yml
Labels: kind/bug, kind/automation

#486 fix: enable release candidates when required
  .github/workflows/release.yml
Labels: kind/bug, area/ci
