Repository kubewarden/kubewarden-controller, pull requests merged in 2023-11, with the labels that each got.

#569 Revert "Merge pull request #566 from viccuad/feat-webhooks-reconciled"
  controllers/admissionpolicy_controller.go
  controllers/clusteradmissionpolicy_controller.go
  controllers/policyserver_controller.go
  internal/pkg/admission/mutating-webhook.go
  internal/pkg/admission/validating-webhook.go
Labels: kind/bug, area/policy

#571 chore(dx): use tilt for development
  .gitignore
  CONTRIBUTING.md
  Tiltfile
  tilt-settings.yaml.example
  tilt.dockerfile
Labels: kind/chore, kind/tech-debt

#578 chore: go linter version bump
  .github/workflows/ci.yml
  Makefile
  controllers/admissionpolicy_controller_test.go
  controllers/clusteradmissionpolicy_controller_test.go
  controllers/policyserver_controller_test.go
  controllers/suite_test.go
  controllers/utils_test.go
  internal/pkg/admission/policy-server-deployment.go
  pkg/apis/policies/v1/webhook_suite_test.go
Labels: kind/chore

#577 chore: remove kube-webhook-wrapper library.
  environment.go
  go.mod
  go.sum
  main.go
  pkg/apis/policies/v1/policyserver_webhook.go
  pkg/apis/policies/v1/webhook_suite_test.go
Labels: kind/chore

#576 feat: reconcile policy webhook configurations
  Makefile
  controllers/admissionpolicy_controller.go
  controllers/admissionpolicy_controller_test.go
  controllers/clusteradmissionpolicy_controller.go
  controllers/clusteradmissionpolicy_controller_test.go
  controllers/policyserver_controller_test.go
  controllers/suite_test.go
  controllers/utils_test.go
  go.mod
  go.sum
  internal/pkg/admission/mutating-webhook.go
  internal/pkg/admission/validating-webhook.go
  internal/pkg/constants/constants.go
Labels: kind/feature

#584 test: add CA bundle assertions in webhook configuration subjects
  controllers/admissionpolicy_controller_test.go
  controllers/clusteradmissionpolicy_controller_test.go
  controllers/utils_test.go
Labels: kind/tech-debt
