Repository kubewarden/kubewarden-controller, pull requests merged in 2024-04, with the labels that each got.

#698 feat: add PDB fields in the policy server spec.
  config/crd/bases/policies.kubewarden.io_admissionpolicies.yaml
  config/crd/bases/policies.kubewarden.io_clusteradmissionpolicies.yaml
  config/crd/bases/policies.kubewarden.io_policyservers.yaml
  config/rbac/role.yaml
  controllers/policyserver_controller.go
  controllers/policyserver_controller_test.go
  controllers/utils_test.go
  internal/pkg/admission/policy-server-pod-disruption-budget.go
  internal/pkg/admission/policy-server-pod-disruption-budget_test.go
  internal/pkg/admission/reconciler.go
  internal/pkg/admission/reconciler_test.go
  main.go
  pkg/apis/policies/v1/policyserver_types.go
  pkg/apis/policies/v1/policyserver_webhook.go
  pkg/apis/policies/v1/policyserver_webhook_test.go
  pkg/apis/policies/v1/zz_generated.deepcopy.go
Labels: kind/feature

#706 chore: Always generate crds on make generate-crds
  docs/crds/README.md
Labels: kind/chore

#708 feat: add limits and requests to PolicyServer
  config/crd/bases/policies.kubewarden.io_policyservers.yaml
  controllers/policyserver_controller_test.go
  controllers/utils_test.go
  docs/crds/CRD-docs-for-docs-repo.md
  internal/pkg/admission/policy-server-deployment.go
  pkg/apis/policies/v1/policyserver_types.go
  pkg/apis/policies/v1/policyserver_webhook.go
  pkg/apis/policies/v1/policyserver_webhook_test.go
  pkg/apis/policies/v1/zz_generated.deepcopy.go
Labels: kind/feature

#713 fix: linter errors and remove requests defaults.
  controllers/policyserver_controller_test.go
  pkg/apis/policies/v1/policyserver_webhook.go
  pkg/apis/policies/v1/policyserver_webhook_test.go
Labels: kind/bug

#714 test: clean up integration tests
  controllers/admissionpolicy_controller_test.go
  controllers/clusteradmissionpolicy_controller_test.go
  controllers/policyserver_controller_test.go
  controllers/utils_test.go
Labels: kind/chore, kind/tech-debt

#715 fix: PolicyServer field.ErrorList validation
  .github/workflows/ci.yml
  pkg/apis/policies/v1/policyserver_webhook.go
  pkg/apis/policies/v1/policyserver_webhook_test.go
Labels: kind/bug, kind/enhancement, kind/tech-debt

#721 fix: remove hardcoded zap development option
  main.go
Labels: kind/bug
