Repository kubewarden/kubewarden-controller, pull requests merged in 2024-03, with the labels that each got.

#666 chore(docs): Kubewarden release template.
  CONTRIBUTING.md
Labels: kind/chore

#674 chore(doc): update checks for Helm chart updates
  CONTRIBUTING.md
Labels: area/documentation, kind/chore

#676 fix: handle enable monitoring boolean flag
  internal/pkg/admission/policy-server-deployment.go
  internal/pkg/admission/policy-server-deployment_test.go
Labels: kind/bug

#675 chore: configure codecov ignore directive and threshold
  Makefile
  codecov.yml
Labels: kind/chore

#677 fix(ci): set prerelease and latest flag properly.
  .github/workflows/release.yml
Labels: kind/bug

#679 fix: increase controllers integration test timeout
  controllers/utils_test.go
Labels: kind/bug

#687 chore: update policy server version used in tests.
  Makefile
Labels: kind/chore

#694 chore: remove ADOPTERS.md from the repository.
  ADOPTERS.md
Labels: kind/chore

#695 feat: Add `PolicyServer.Spec.Affinity` field, refresh crds
  config/crd/bases/policies.kubewarden.io_policyservers.yaml
  internal/pkg/admission/policy-server-deployment.go
  internal/pkg/admission/policy-server-deployment_test.go
  pkg/apis/policies/v1/policyserver_types.go
  pkg/apis/policies/v1/zz_generated.deepcopy.go
Labels: kind/feature
