Repository kubewarden/kubewarden-controller, pull requests merged in 2024-09, with the labels that each got.

#867 fix(Tiltfile): remove overriding helm webhooks with kustomize ones
  Tiltfile
Labels: kind/bug

#868 chore: disable cert-manager from scaffolded kustomize config
  config/default/kustomization.yaml
Labels: kind/chore

#866 fix: generate certificates with the same settings as helm helper functions
  internal/certs/certs.go
Labels: kind/bug, kind/chore, kind/feature

#873 Revert "feat: add feature flag for policy groups."
  Tiltfile
  cmd/main.go
  internal/constants/constants.go
Labels: kind/feature

#870 feat: validate PolicyGroup expressions
  api/policies/v1/admissionpolicy_webhook.go
  api/policies/v1/admissionpolicygroup_webhook.go
  api/policies/v1/clusteradmissionpolicy_webhook.go
  api/policies/v1/clusteradmissionpolicygroup_webhook.go
  api/policies/v1/policy_utils_test.go
  api/policies/v1/policy_validation.go
  api/policies/v1/policy_validation_test.go
  api/policies/v1/policygroup_validation.go
  api/policies/v1/policygroup_validation_test.go
Labels: kind/feature

#878 fix: policy group members as map
  api/policies/v1/admissionpolicy_types.go
  api/policies/v1/admissionpolicygroup_types.go
  api/policies/v1/clusteradmissionpolicy_types.go
  api/policies/v1/clusteradmissionpolicygroup_types.go
  api/policies/v1/policy.go
  api/policies/v1/policy_types.go
  api/policies/v1/policy_utils_test.go
  api/policies/v1/policygroup_validation.go
  api/policies/v1/policygroup_validation_test.go
  api/policies/v1/zz_generated.deepcopy.go
  config/crd/bases/policies.kubewarden.io_admissionpolicygroups.yaml
  config/crd/bases/policies.kubewarden.io_clusteradmissionpolicygroups.yaml
  internal/controller/policyserver_controller_configmap.go
  internal/controller/policyserver_controller_test.go
  internal/controller/utils_test.go
Labels: kind/enhancement

#880 feat: validate policy group members names.
  api/policies/v1/policygroup_validation.go
  api/policies/v1/policygroup_validation_test.go
Labels: kind/feature

#883 fix: cluster admission policy and policygroup namspaceSelector getter
  Makefile
  api/policies/v1/admissionpolicy_types.go
  api/policies/v1/admissionpolicygroup_types.go
  api/policies/v1/clusteradmissionpolicy_types.go
  api/policies/v1/clusteradmissionpolicy_types_test.go
  api/policies/v1/clusteradmissionpolicygroup_types.go
  api/policies/v1/policy.go
  internal/controller/clusteradmissionpolicy_controller_test.go
  internal/controller/clusteradmissionpolicygroup_controller_test.go
  internal/controller/policy_subreconciler_webhook.go
Labels: kind/bug

#885 fix: use a different name for ClusterAdmissionpolicyGroup unique name
  api/policies/v1/admissionpolicygroup_types.go
  api/policies/v1/clusteradmissionpolicygroup_types.go
Labels: kind/bug

#890 fix: policy group plural name
  api/policies/v1/admissionpolicygroup_webhook.go
  api/policies/v1/clusteradmissionpolicygroup_webhook.go
  config/webhook/manifests.yaml
  internal/controller/policyserver_controller.go
Labels: kind/bug

#891 refactor: remove watches used only by integration tests
  internal/controller/admissionpolicy_controller.go
  internal/controller/admissionpolicygroup_controller.go
  internal/controller/clusteradmissionpolicy_controller.go
  internal/controller/clusteradmissionpolicygroup_controller.go
  internal/controller/policy_subreconciler.go
Labels: kind/tech-debt

#892 test: add policy deletion -> webhook deletion tests
  internal/controller/admissionpolicy_controller_test.go
  internal/controller/admissionpolicygroup_controller_test.go
  internal/controller/clusteradmissionpolicy_controller_test.go
  internal/controller/clusteradmissionpolicygroup_controller_test.go
Labels: kind/tech-debt

#893 fix: add group annotation to WebhookConfiguration and filter watch requests
  internal/constants/constants.go
  internal/controller/admissionpolicy_controller.go
  internal/controller/admissionpolicygroup_controller.go
  internal/controller/admissionpolicygroup_controller_test.go
  internal/controller/clusteradmissionpolicy_controller.go
  internal/controller/clusteradmissionpolicygroup_controller.go
  internal/controller/clusteradmissionpolicygroup_controller_test.go
  internal/controller/policy_subreconciler.go
  internal/controller/policy_subreconciler_webhook.go
Labels: kind/bug
