Repository kubewarden/kubewarden-controller, pull requests merged in 2024-07, with the labels that each got.

#793 feat: policy server deployment tolerations.
  api/policies/v1/policyserver_types.go
  api/policies/v1/zz_generated.deepcopy.go
  api/policies/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/policies.kubewarden.io_policyservers.yaml
  internal/controller/policyserver_controller_deployment.go
  internal/controller/policyserver_controller_test.go
Labels: kind/feature

#788 test: split envtest/real cluster tests
  .github/workflows/ci.yml
  CONTRIBUTING.md
  Makefile
  internal/controller/admissionpolicy_controller_test.go
  internal/controller/clusteradmissionpolicy_controller_test.go
  internal/controller/policyserver_controller_test.go
  internal/controller/suite_test.go
  internal/controller/utils_test.go
Labels: kind/tech-debt

#795 fix: rename some consts and functions.
  api/policies/v1/policyserver_types.go
  internal/controller/policyserver_controller.go
  internal/controller/policyserver_controller_cert_secret.go
  internal/controller/policyserver_controller_test.go
  internal/controller/utils_test.go
Labels: kind/bug

#800 build: add ginkgo dep to makefile
  .github/workflows/ci.yml
  Makefile
Labels: kind/chore, area/ci

#807 feat: use stricter go linter configuration.
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  api/policies/v1/admissionpolicy_types.go
  api/policies/v1/admissionpolicy_webhook.go
  api/policies/v1/clusteradmissionpolicy_types.go
  api/policies/v1/clusteradmissionpolicy_webhook.go
  api/policies/v1/groupversion_info.go
  api/policies/v1/policy.go
  api/policies/v1/policy_validation.go
  api/policies/v1/policyserver_types.go
  api/policies/v1/policyserver_webhook.go
  api/policies/v1alpha2/admissionpolicy_types.go
  api/policies/v1alpha2/clusteradmissionpolicy_types.go
  api/policies/v1alpha2/groupversion_info.go
  api/policies/v1alpha2/policy.go
  api/policies/v1alpha2/policyserver_types.go
  cmd/main.go
  config/crd/bases/policies.kubewarden.io_admissionpolicies.yaml
  config/crd/bases/policies.kubewarden.io_clusteradmissionpolicies.yaml
  config/crd/bases/policies.kubewarden.io_policyservers.yaml
  internal/certs/certs.go
  internal/constants/constants.go
  internal/controller/admissionpolicy_controller.go
  internal/controller/admissionpolicy_controller_test.go
  internal/controller/clusteradmissionpolicy_controller.go
  internal/controller/clusteradmissionpolicy_controller_test.go
  internal/controller/policy_subreconciler.go
  internal/controller/policy_subreconciler_webhook.go
  internal/controller/policyserver_controller.go
  internal/controller/policyserver_controller_cert_secret.go
  internal/controller/policyserver_controller_configmap.go
  internal/controller/policyserver_controller_deployment.go
  internal/controller/policyserver_controller_service.go
  internal/controller/policyserver_controller_test.go
  internal/controller/suite_test.go
  internal/controller/utils_test.go
  internal/metrics/metrics.go
Labels: kind/feature

#816 fix: tilt hot reloading
  Tiltfile
Labels: kind/bug

#814 feat: Add new `spec.matchConditions` to (Cluster)AdmissionPolicies
  api/policies/v1/admissionpolicy_types.go
  api/policies/v1/clusteradmissionpolicy_types.go
  api/policies/v1/policy.go
  api/policies/v1/policy_types.go
  api/policies/v1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/policies.kubewarden.io_admissionpolicies.yaml
  config/crd/bases/policies.kubewarden.io_clusteradmissionpolicies.yaml
  docs/crds/CRD-docs-for-docs-repo.md
  internal/controller/admissionpolicy_controller.go
  internal/controller/admissionpolicy_controller_test.go
  internal/controller/clusteradmissionpolicy_controller.go
  internal/controller/clusteradmissionpolicy_controller_test.go
  internal/controller/policy_subreconciler.go
  internal/controller/policy_subreconciler_webhook.go
  internal/controller/suite_test.go
  internal/controller/utils_test.go
  internal/featuregates/featuregates.go
Labels: kind/feature

#823 feat: verify MatchConditons, return aggregate errors on validation
  .golangci.yml
  api/policies/v1/admissionpolicy_webhook.go
  api/policies/v1/admissionpolicy_webhook_test.go
  api/policies/v1/clusteradmissionpolicy_webhook.go
  api/policies/v1/clusteradmissionpolicy_webhook_test.go
  api/policies/v1/policy_utils_test.go
  api/policies/v1/policy_validation.go
  api/policies/v1/policy_validation_matchconditions.go
  api/policies/v1/policy_validation_test.go
  go.mod
  go.sum
Labels: kind/feature

#825 fix: add generate-crds target.
  Makefile
Labels: kind/bug

#827 chore: Refresh CRD-docs-for-docs-repo.md
  api/policies/v1/policy_types.go
  config/crd/bases/policies.kubewarden.io_admissionpolicies.yaml
  config/crd/bases/policies.kubewarden.io_clusteradmissionpolicies.yaml
  config/crd/bases/policies.kubewarden.io_policyservers.yaml
  docs/crds/CRD-docs-for-docs-repo.md
Labels: kind/chore

#835 deps: Bump google.golang.org/grpc to > v1.64.1
  Makefile
  go.mod
  go.sum
Labels: area/dependencies
