Repository kubewarden/kubewarden-controller, pull requests merged in 2024-06, with the labels that each got.

#759 fix: use domain qualified finalizers.
  controllers/admissionpolicy_controller_test.go
  controllers/clusteradmissionpolicy_controller_test.go
  controllers/policy_utils.go
  controllers/policyserver_controller.go
  controllers/policyserver_controller_test.go
  internal/pkg/admission/testing_common.go
  internal/pkg/constants/constants.go
Labels: kind/bug

#783 fix: bump cert NotAfter to 10 years
  internal/pkg/admissionregistration/cert.go
Labels: kind/bug

#779 fix: its not necessary add the finalizer in the reconciliation loop.
  controllers/admissionpolicy_controller_test.go
  controllers/clusteradmissionpolicy_controller_test.go
  controllers/policy_utils.go
  controllers/policyserver_controller.go
  controllers/policyserver_controller_test.go
Labels: kind/bug

#777 refactor: certificates generation package and secrets
  .golangci.yml
  controllers/policyserver_controller_test.go
  controllers/utils_test.go
  internal/pkg/admission/policy-server-ca-secret.go
  internal/pkg/admission/policy-server-ca-secret_test.go
  internal/pkg/admission/reconciler.go
  internal/pkg/admission/testing_common.go
  internal/pkg/admissionregistration/ca.go
  internal/pkg/admissionregistration/key.go
  internal/pkg/certs/certs.go
Labels: kind/tech-debt

#785 refactor: policy server reconciler
  .golangci.yml
  cmd/main.go
  internal/admission/policy-server-configmap_test.go
  internal/admission/policy-server-deployment_test.go
  internal/admission/policy-server-error.go
  internal/admission/policy-server-error_test.go
  internal/admission/policy-server-pod-disruption-budget_test.go
  internal/admission/policy-server-service_test.go
  internal/admission/reconciler.go
  internal/admission/reconciler_test.go
  internal/admission/testing_common.go
  internal/controller/admissionpolicy_controller.go
  internal/controller/clusteradmissionpolicy_controller.go
  internal/controller/policyserver_controller.go
  internal/controller/policyserver_controller_ca_secret.go
  internal/controller/policyserver_controller_configmap.go
  internal/controller/policyserver_controller_deployment.go
  internal/controller/policyserver_controller_pdb.go
  internal/controller/policyserver_controller_service.go
  internal/controller/policyserver_controller_test.go
  internal/controller/policystatus_utils.go
  internal/controller/suite_test.go
Labels: kind/chore, kind/tech-debt
