Repository kubewarden/kubewarden-controller, pull requests merged in 2024-12, with the labels that each got.

#932 chore: Kubewarden release issue template.
  .github/ISSUE_TEMPLATE/kubewarden-release.yml
Labels: kind/enhancement, kind/chore

#934 Remote otel collector configuration
  Tiltfile
  cmd/main.go
  internal/controller/policy_subreconciler.go
  internal/controller/policyserver_controller.go
  internal/controller/policyserver_controller_deployment.go
  internal/metrics/metrics.go
  tilt-settings.yaml.example
Labels: kind/breaking-change

#948 build(deps): bump x/net to v0.33.0
  go.mod
  go.sum
Labels: area/dependencies, dependencies

#949 chore(deps): update ginkgo binary
  Makefile
Labels: area/dependencies, kind/chore
