Repository kubewarden/kubewarden-controller, pull requests merged in 2024-10, with the labels that each got.

#901 fix: do not exit when k8s' matchConditions are not available
  cmd/main.go
Labels: kind/bug

#896 feat: shortName for the CRDs.
  api/policies/v1/admissionpolicy_types.go
  api/policies/v1/admissionpolicygroup_types.go
  api/policies/v1/clusteradmissionpolicy_types.go
  api/policies/v1/clusteradmissionpolicygroup_types.go
  api/policies/v1/policyserver_types.go
  api/policies/v1alpha2/admissionpolicy_types.go
  api/policies/v1alpha2/clusteradmissionpolicy_types.go
  api/policies/v1alpha2/policyserver_types.go
  config/crd/bases/policies.kubewarden.io_admissionpolicies.yaml
  config/crd/bases/policies.kubewarden.io_admissionpolicygroups.yaml
  config/crd/bases/policies.kubewarden.io_clusteradmissionpolicies.yaml
  config/crd/bases/policies.kubewarden.io_clusteradmissionpolicygroups.yaml
  config/crd/bases/policies.kubewarden.io_policyservers.yaml
Labels: kind/enhancement, area/crd, kind/feature

#894 refactor: simplify wehbook configuration controller handlers
  internal/constants/constants.go
  internal/controller/admissionpolicy_controller.go
  internal/controller/admissionpolicy_controller_test.go
  internal/controller/admissionpolicygroup_controller.go
  internal/controller/admissionpolicygroup_controller_test.go
  internal/controller/clusteradmissionpolicy_controller.go
  internal/controller/clusteradmissionpolicy_controller_test.go
  internal/controller/clusteradmissionpolicygroup_controller.go
  internal/controller/clusteradmissionpolicygroup_controller_test.go
  internal/controller/policy_subreconciler.go
  internal/controller/policy_subreconciler_webhook.go
Labels: kind/tech-debt
