Repository kubewarden/kubewarden-controller, pull requests merged in 2024-05, with the labels that each got.

#730 Update controller code to use the controller-runtime helper function to create or update resources
  Makefile
  config/rbac/role.yaml
  controllers/admissionpolicy_controller.go
  controllers/clusteradmissionpolicy_controller.go
  controllers/policyserver_controller_test.go
  internal/pkg/admission/mutating-webhook.go
  internal/pkg/admission/policy-server-configmap.go
  internal/pkg/admission/policy-server-configmap_test.go
  internal/pkg/admission/policy-server-deployment.go
  internal/pkg/admission/policy-server-deployment_test.go
  internal/pkg/admission/policy-server-pod-disruption-budget_test.go
  internal/pkg/admission/policy-server-service.go
  internal/pkg/admission/policy-server-service_test.go
  internal/pkg/admission/reconciler_test.go
  internal/pkg/admission/validating-webhook.go
Labels: kind/tech-debt

#720 feat: use owner reference with policy server resources.
  Makefile
  config/crd/bases/policies.kubewarden.io_admissionpolicies.yaml
  config/crd/bases/policies.kubewarden.io_clusteradmissionpolicies.yaml
  config/crd/bases/policies.kubewarden.io_policyservers.yaml
  controllers/policyserver_controller.go
  controllers/policyserver_controller_test.go
  controllers/utils_test.go
  internal/pkg/admission/policy-server-ca-secret.go
  internal/pkg/admission/policy-server-ca-secret_test.go
  internal/pkg/admission/policy-server-configmap.go
  internal/pkg/admission/policy-server-deployment.go
  internal/pkg/admission/policy-server-deployment_test.go
  internal/pkg/admission/policy-server-service.go
  internal/pkg/admission/policy-server-service_test.go
  internal/pkg/admission/policy-server_integration_test.go
  internal/pkg/admission/reconciler.go
  internal/pkg/admission/testing_common.go
Labels: kind/tech-debt, kind/feature

#740 fix: patch webhooks not update them.
  internal/pkg/admission/mutating-webhook.go
  internal/pkg/admission/validating-webhook.go
Labels: kind/bug

#741 fix: cache configMap resources.
  controllers/policyserver_controller_test.go
  main.go
Labels: kind/bug

#750 fix: do not overwrite PolicyServer annotations and labels
  internal/pkg/admission/policy-server-deployment.go
Labels: kind/bug

#751 dev: fix the tilt development file
  Tiltfile
Labels: kind/bug

#754 chore: add Kubewarden repository badges.
  README.md
Labels: kind/chore

#753 refactor: use only `CreateOrPatch`
  internal/pkg/admission/policy-server-ca-secret.go
  internal/pkg/admission/policy-server-pod-disruption-budget.go
  internal/pkg/admission/policy-server-service.go
Labels: kind/tech-debt
