Repository kubewarden/kubewarden-controller, pull requests merged in 2025-01, with the labels that each got.

#952 fix: rename "url" field into "module".
  Makefile
  internal/controller/policyserver_controller_configmap.go
  internal/controller/policyserver_controller_test.go
  internal/controller/utils_test.go
Labels: kind/bug

#955 feat(test): use builder to build test objects.
  internal/controller/admissionpolicy_controller_test.go
  internal/controller/admissionpolicygroup_controller_test.go
  internal/controller/clusteradmissionpolicy_controller_test.go
  internal/controller/clusteradmissionpolicygroup_controller_test.go
  internal/controller/factories_test.go
  internal/controller/policyserver_controller_test.go
  internal/controller/utils_test.go
Labels: area/qa, kind/feature

#957 Webhook integration tests and clean up MatchCondition validation code
  .golangci.yml
  Makefile
  api/policies/v1/admissionpolicy_webhook_test.go
  api/policies/v1/admissionpolicygroup_webhook_test.go
  api/policies/v1/clusteradmissionpolicy_webhook_test.go
  api/policies/v1/clusteradmissionpolicygroup_webhook_test.go
  api/policies/v1/factories.go
  api/policies/v1/policy_utils_test.go
  api/policies/v1/policy_validation.go
  api/policies/v1/policy_validation_matchconditions.go
  api/policies/v1/policy_validation_test.go
  internal/controller/admissionpolicy_controller_test.go
  internal/controller/admissionpolicygroup_controller_test.go
  internal/controller/clusteradmissionpolicy_controller_test.go
  internal/controller/clusteradmissionpolicygroup_controller_test.go
  internal/controller/factories_test.go
  internal/controller/policyserver_controller_test.go
  internal/controller/utils_test.go
Labels: area/qa, kind/feature

#962 chore(ci): use common renovate bot configuration.
  renovate.json
Labels: kind/chore

#963 chore: move release template to the org repository.
  .github/ISSUE_TEMPLATE/kubewarden-release.yml
Labels: kind/chore

#985 fix: stricter checks on AdmissionPolicy and AdmissionPolicyGroup rules
  api/policies/v1/policy_validation.go
  api/policies/v1/policy_validation_test.go
  config/crd/bases/policies.kubewarden.io_policyservers.yaml
Labels: kind/bug
