Repository kubewarden/kubewarden-controller, pull requests merged in 2025-02, with the labels that each got.

#992 build(deps): move cel-go dependecy to indirect
  go.mod
  go.sum
Labels: area/dependencies

#1005 build(deps): disable cel-go bot updates
  go.mod
  renovate.json
Labels: area/dependencies, dependencies

#1000 feat: add mTLS support
  cmd/main.go
  internal/constants/constants.go
  internal/controller/admissionpolicy_controller_test.go
  internal/controller/admissionpolicygroup_controller_test.go
  internal/controller/clusteradmissionpolicy_controller_test.go
  internal/controller/clusteradmissionpolicygroup_controller_test.go
  internal/controller/policyserver_controller.go
  internal/controller/policyserver_controller_deployment.go
  internal/controller/policyserver_controller_test.go
  internal/controller/suite_test.go
  internal/controller/utils_test.go
Labels: kind/feature

#1010 Revert "dropme: green ci"
  internal/controller/policyserver_controller_deployment.go
  internal/controller/policyserver_controller_test.go
Labels: kind/chore

#1011 fix: mount and configure internal CA only with mTLS enabled
  internal/controller/policyserver_controller_deployment.go
Labels: kind/bug

#1027 fix: client-ca filepath
  cmd/main.go
Labels: kind/bug, area/certificates
